
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    pathType: Prefix
    hostname: argocd.172.40.255.200.nip.io
    https: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol:  "HTTPS"
